api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    # formats:
    #     jsonld: ['application/ld+json']
    patch_formats:
        json: ['application/merge-patch+json']
        jsonld: ['application/ld+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            items_per_page: 10
